name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  go_router: ^16.1.0
  json_annotation: ^4.9.0

  # --- FlutterFire (aligned versions) ---
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.6
  # If you actually need generative AI via Firebase, use:
  # firebase_vertexai: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cardimages/
