// lib/game_data/game_data_manager.dart
import 'package:myapp/game_data/card_definition.dart';

/// Simple in-memory card list for testing.
/// Swap/expand with your real data later.
class GameDataManager {
  static final List<CardDefinition> cards = [
    // --- Creatures ---
    CardDefinition(
      id: 'c-watcher-001',
      name: 'Watcher of the Vault',
      description: 'A vigilant guardian, ever watchful.',
      typeId: 'creature',
      cost: 2,
      attack: 2,
      defense: 2,
      abilities: const [],
      categoryId: 'event',
      classId: 'illuminati',
      rarity: CardRarity.common,
      faction: CardFaction.underground,
      tags: const ['watcher', 'guardian'],
      imagePath: 'assets/cardimages/watcher_of_the_vault.png',
    ),
    CardDefinition(
      id: 'c-mindspy-002',
      name: 'Mindspy Operative',
      description: 'An agent skilled in extracting secrets.',
      typeId: 'creature',
      cost: 3,
      attack: 3,
      defense: 2,
      abilities: const [],
      categoryId: 'conspiracy',
      classId: 'grey_aliens',
      rarity: CardRarity.rare,
      faction: CardFaction.media,
      tags: const ['spy', 'operative'],
      imagePath: 'assets/cardimages/mindspy_operative.png',
    ),
    CardDefinition(
      id: 'c-sentinel-003',
      name: 'Silent Sentinel',
      description: 'A silent enforcer standing guard.',
      typeId: 'creature',
      cost: 4,
      attack: 4,
      defense: 4,
      abilities: const [],
      categoryId: 'event',
      classId: 'illuminati',
      rarity: CardRarity.epic,
      faction: CardFaction.gov,
      tags: const ['sentinel', 'defender'],
      imagePath: 'assets/cardimages/silent_sentinel.png',
    ),

    // --- Spells ---
    CardDefinition(
      id: 's-boost-101',
      name: 'Whispered Tactics',
      description: 'Bolster a creature with whispered schemes.',
      typeId: 'spell',
      cost: 1,
      abilities: const [CardAbilityType.attackBoost],
      categoryId: 'scheme',
      classId: 'conspirator',
      rarity: CardRarity.common,
      faction: CardFaction.media,
      tags: const ['buff', 'attack'],
      imagePath: 'assets/cardimages/whispered_tactics.png',
    ),
    CardDefinition(
      id: 's-shield-102',
      name: 'Hidden Shield',
      description: 'An unseen shield grants protection.',
      typeId: 'spell',
      cost: 1,
      abilities: const [CardAbilityType.defenseBoost],
      categoryId: 'scheme',
      classId: 'defender',
      rarity: CardRarity.common,
      faction: CardFaction.underground,
      tags: const ['buff', 'defense'],
      imagePath: 'assets/cardimages/hidden_shield.png',
    ),
    CardDefinition(
      id: 's-draw-103',
      name: 'Redacted Files',
      description: 'Unearth secrets hidden from the public.',
      typeId: 'spell',
      cost: 1,
      abilities: const [CardAbilityType.drawCard],
      categoryId: 'conspiracy',
      classId: 'research',
      rarity: CardRarity.rare,
      faction: CardFaction.media,
      tags: const ['card advantage'],
      imagePath: 'assets/cardimages/redacted_files.png',
    ),
    CardDefinition(
      id: 's-discard-104',
      name: 'Intercept Transmission',
      description: 'Cut off the enemy’s communication.',
      typeId: 'spell',
      cost: 2,
      abilities: const [CardAbilityType.discardOpponentCard],
      categoryId: 'event',
      classId: 'spy',
      rarity: CardRarity.rare,
      faction: CardFaction.gov,
      tags: const ['discard', 'control'],
      imagePath: 'assets/cardimages/intercept_transmission.png',
    ),
    CardDefinition(
      id: 's-remove-105',
      name: 'Vanishing Act',
      description: 'A creature mysteriously disappears.',
      typeId: 'spell',
      cost: 3,
      abilities: const [CardAbilityType.removeTargetCreatureFromPlay],
      categoryId: 'event',
      classId: 'illusionist',
      rarity: CardRarity.epic,
      faction: CardFaction.underground,
      tags: const ['removal', 'control'],
      imagePath: 'assets/cardimages/vanishing_act.png',
    ),
    CardDefinition(
      id: 's-eco-106',
      name: 'Resource Cache',
      description: 'A hidden cache bolsters your resources.',
      typeId: 'spell',
      cost: 2,
      abilities: const [CardAbilityType.gainResources],
      categoryId: 'scheme',
      classId: 'supply',
      rarity: CardRarity.common,
      faction: CardFaction.gov,
      tags: const ['resource', 'economy'],
      imagePath: 'assets/cardimages/resource_cache.png',
    ),
    CardDefinition(
      id: 's-heal-107',
      name: 'Field Medic',
      description: 'Restores vitality to your forces.',
      typeId: 'spell',
      cost: 2,
      abilities: const [CardAbilityType.heal],
      categoryId: 'event',
      classId: 'support',
      rarity: CardRarity.common,
      faction: CardFaction.media,
      tags: const ['heal', 'support'],
      imagePath: 'assets/cardimages/field_medic.png',
    ),
    CardDefinition(
      id: 's-bolt-108',
      name: 'Blackout Pulse',
      description: 'A disruptive energy blast strikes your foe.',
      typeId: 'spell',
      cost: 2,
      abilities: const [CardAbilityType.dealDamageX],
      categoryId: 'event',
      classId: 'tech',
      rarity: CardRarity.epic,
      faction: CardFaction.underground,
      tags: const ['damage', 'pulse'],
      imagePath: 'assets/cardimages/blackout_pulse.png',
    ),
  ];
}
